config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    devise_for :users, controllers: {
        registrations: 'users/registrations'
      }


    resources :users
    resources :books


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="flash">
    <p><%= flash[:alert] %></p>
  </div>
  <% end %>



    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>

          <ul class="nav navbar-nav navbar-right small">
            <% if user_signed_in? %>
              <li>
                <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home", "aria-hidden": true %>
              </li>
              <li>
                <%= link_to ' Users', users_path, class: "glyphicon glyphicon-user users", "aria-hidden": true %>
              </li>
              <li>
                <%= link_to ' Books', books_path, class: "glyphicon glyphicon-book", "aria-hidden": true %>
              </li>
              <li>
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-share", "aria-hidden": true %>
              </li>

            <% else %>
              <li>
                <%= link_to " Home", root_path, class: "glyphicon glyphicon-home home", "aria-hidden": true %>
                <span ></span>
              </li>
              <li>
                <%= link_to " About", home_about_path, class: "glyphicon glyphicon-link about", "aria-hidden": true %>
              </li>
              <li>
                <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit", "aria-hidden": true %>
              </li>
              <li>
                <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-share", "aria-hidden": true %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>



  <%= yield %>

     <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>




</body>
</html>